django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # django自带的后台管理
    url(r'^admin/', admin.site.urls),
    # xadmin的配置
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # 商品部分
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # 用户账户模块
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # 系统模块
    url(r'^sys/', include('system.urls', namespace='system')),
    # 个人中心
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

mall/models.py
import uuid

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from django.db.models import F

from accounts.models import User
from system.models import ImageFile
from utils import constants


class Classify(models.Model):
    """ 商品的分类 """
    uid = models.UUIDField('分类ID', default=uuid.uuid4, editable=True)
    parent = models.ForeignKey('self', related_name='children', null=True, blank=True)
    img = models.ImageField('分类主图', upload_to='classify')
    code = models.CharField('编码', max_length=32, null=True, blank=True)
    name = models.CharField('名称', max_length=12)
    desc = models.CharField('描述', max_length=64, null=True, blank=True)
    reorder = models.SmallIntegerField('排序', default=0)
    is_valid = models.BooleanField('是否有效', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'mall_classify'
        verbose_name = '商品分类'
        verbose_name_plural = '商品分类'
        ordering = ['-reorder']

    def __str__(self):
        return '{}:{}'.format(self.code, self.name)


class Tag(models.Model):
    """ 商品的标签 """

    uid = models.UUIDField('标签ID', default=uuid.uuid4, editable=True)
    img = models.ImageField('主图', upload_to='tags', null=True, blank=True)
    code = models.CharField('编码', max_length=32, null=True, blank=True)
    name = models.CharField('名称', max_length=12)
    reorder = models.SmallIntegerField('排序', default=0)
    is_valid = models.BooleanField('是否有效', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'mall_tag'
        verbose_name = '商品标签'
        verbose_name_plural = '商品标签'
        ordering = ['-reorder']

    def __str__(self):
        return '{}:{}'.format(self.code, self.name)


class Product(models.Model):
    """ 商品 """
    uid = models.UUIDField('商品ID', default=uuid.uuid4, editable=False)
    name = models.CharField('商品名称', max_length=128)
    desc = models.CharField('简单描述', max_length=256, null=True, blank=True)
    # content = models.TextField('商品描述')
    # 富文本
    content = RichTextField('商品描述')

    types = models.SmallIntegerField('商品类型',
                                     choices=constants.PRODUCT_TYPES_CHOICES,
                                     default=constants.PRODUCT_TYPE_ACTUAL)
    price = models.IntegerField('兑换价格（积分兑换）')
    origin_price = models.FloatField('原价')
    img = models.ImageField('主图', upload_to='%Y%m/product')
    buy_link = models.CharField('购买链接', max_length=256, null=True, blank=True)
    reorder = models.SmallIntegerField('排序', default=0)
    status = models.SmallIntegerField('商品状态', default=constants.PRODUCT_STATUS_LOST,
                                      choices=constants.PRODUCT_STATUS_CHOICES)

    sku_count = models.IntegerField('库存', default=0)
    ramain_count = models.IntegerField('剩余库存', default=0)
    view_count = models.IntegerField('浏览次数',default=0)
    score = models.FloatField('商品的评分', default=10.0)

    is_valid = models.BooleanField('是否有效', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    tags = models.ManyToManyField(Tag, verbose_name='标签',
                                  related_name='tags',
                                  null=True,
                                  blank=True
                                  )
    classes = models.ManyToManyField(Classify,
                                     verbose_name='分类',
                                     related_name='classes',
                                     null=True,
                                     blank=True)

    banners = GenericRelation(ImageFile, verbose_name='banner图',
                              related_query_name='banners')

    class Meta:
        db_table = 'mall_product'
        verbose_name = '商品信息'
        verbose_name_plural = '商品信息'
        ordering = ['-reorder']

    def update_store_count(self, count):
        """
        更改商品的库存信息
        :param count:
        :return:
        """
        self.ramain_count = F('ramain_count') - abs(count)
        self.save()
        self.refresh_from_db()

    def __str__(self):
        return self.name


mall/forms.py
from django import forms

from mall.models import Product


class ProductAdminForm(forms.ModelForm):
    """ 商品编辑 """

    class Meta:
        model = Product
        exclude = ['created_at', 'updated_at']
        widgets = {
            # 修改表单的输入界面（下拉，radio）
            'types': forms.RadioSelect
        }

    def clean_price(self):
        """ 验证商品的价格 """
        price = self.cleaned_data['price']
        if int(price) <= 0:
            raise forms.ValidationError('销售价格不能小于0')
        return price

mall/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import ListView

from mall.models import Product
from utils import constants


def product_list(request, template_name='product_list.html'):
    """ 商品列表 """
    prod_list = Product.objects.filter(
        status=constants.PRODUCT_STATUS_SELL,
        is_valid=True)
    # 按名称搜索
    name = request.GET.get('name', '')
    if name:
        prod_list = prod_list.filter(name__icontains=name)
    return render(request, template_name, {
        'prod_list': prod_list
    })


def product_detail(request, pk, template_name='product_detail.html'):
    """ 商品详情 """
    prod_obj = get_object_or_404(Product, uid=pk, is_valid=True)
    # 用户的默认地址
    user = request.user
    default_addr = None
    if user.is_authenticated:
        default_addr = user.default_addr
    return render(request, template_name, {
        'prod_obj': prod_obj,
        'default_addr': default_addr
    })


class ProductList(ListView):
    """" 商品列表 """
    # 每页放多少条数据
    paginate_by = 6
    # 模板位置
    template_name = 'product_list.html'

    def get_queryset(self):
        query = Q(status=constants.PRODUCT_STATUS_SELL,
            is_valid=True)
        # 按名称搜索
        name = self.request.GET.get('name', '')
        if name:
            query = query & Q(name__icontains=name)

        # 按标签进行搜索
        tag = self.request.GET.get('tag', '')
        if tag:
            query = query & Q(tags__code=tag)

        # 按照分类进行搜索
        cls = self.request.GET.get('cls', '')
        if cls:
            query = query & Q(classes__code=cls)
        return Product.objects.filter(query)

    def get_context_data(self, **kwargs):
        """ 添加变量到上下文 """
        context = super().get_context_data(**kwargs)
        context['params'] = self.request.GET.dict()
        return context


def prod_classify(request):
    """ 商品分类 """
    return render(request, 'prod_classify.html', {

    })

mall/templates/product_list.html
{% extends 'base.html' %}
{% block title %}
<title>产品列表</title>
{% endblock %}
{% block container %}
<!--顶部搜索-->
<header class='weui-header fixed-top'>
  <div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form" method="get" action=".">
      <div class="weui-search-bar__box">
        <i class="weui-icon-search"></i>
        <input type="search" class="weui-search-bar__input"
               id="searchInput"
               name="name"
               placeholder="搜索您想要的商品" required>
        <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
      </div>
      <label class="weui-search-bar__label" id="searchText" style="transform-origin: 0px 0px 0px; opacity: 1; transform: scale(1, 1);">
        <i class="weui-icon-search"></i>
        <span>搜索您想要的商品</span>
      </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
  </div>
  <div class="pro-sort">
    <div class="weui-flex">
      <div class="weui-flex__item"><div class="placeholder NormalCss">综合</div></div>
      <div class="weui-flex__item"><div class="placeholder SortAscCss">按销量</div></div>
      <div class="weui-flex__item"><div class="placeholder SortDescCss">按价格</i></div></div>
    </div>
  </div>
</header>
<!--主体-->
<div class="weui-content" style="padding-top:85px;">
  <!--产品列表--滑动加载-->
  <div class="weui-pull-to-refresh__layer">
    <div class='weui-pull-to-refresh__arrow'></div>
    <div class='weui-pull-to-refresh__preloader'></div>
    <div class="down">下拉刷新</div>
    <div class="up">释放刷新</div>
    <div class="refresh">正在刷新</div>
  </div>
  <div id="list" class='demos-content-padded proListWrap'>

  </div>
  <div class="weui-loadmore" id="loading">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
  </div>
 
  
</div>

{% endblock %}
{% block footer %}
<script>
    var loading = false;  // 是否正在加载中
    var page = 1; // 当前页
    var noMore = false; // 是否还有下一页
    /**
     * 封装函数，异步取数据
     * @param callback
     */
    function loadData(callback) {
        if(loading) return;
        if(noMore) return;
        loading = true;
        $('#loading').show();
        $.ajax({
            url: '{% url 'mall:product_load_list' %}',
            data: {
                page: page,
                name: "{{ params.name|default_if_none:'' }}",
                cls: "{{ params.cls|default_if_none:'' }}",
                tag: "{{ params.tag|default_if_none:'' }}"
            },
            success: function(rest) {
                // 添加HTML片段到内容区
                $('#list').append(rest);
                page++;  // 页码加1
                loading = false;
                $('#loading').hide()
                // 如果有回调函数，则调用
                if (callback) {
                    callback()
                }
            }
        })
    }
      $(document.body).pullToRefresh().on("pull-to-refresh", function() {
          $("#list").empty();
          page = 1;
          noMore = false;
          loadData(function () {
              $(document.body).pullToRefreshDone();
          })
      });
      // infinite

      $(document.body).infinite(200).on("infinite", function() {
        loadData(); // 加载数据
      });
      loadData();//默认加载第一页
</script>
{% endblock %}

mall/templates/product_load_list.html
{% for item in object_list %}
<div class="pro-items">
  <a href="{% url 'mall:product_detail' item.uid %}" class="weui-media-box weui-media-box_appmsg">
    <div class="weui-media-box__hd">
        <img class="weui-media-box__thumb" src="{{ item.img.url }}" alt="">
    </div>
    <div class="weui-media-box__bd">
      <h1 class="weui-media-box__desc">{{ item.name }}</h1>
      <div class="wy-pro-pri">¥<em class="num font-15">{{ item.price }}</em></div>
      <ul class="weui-media-box__info prolist-ul">
        <li class="weui-media-box__info__meta"><em class="num">0</em>条评价</li>
        <li class="weui-media-box__info__meta"><em class="num">100%</em>好评</li>
      </ul>
    </div>
  </a>
</div>
{% endfor %}

mall/templates/shopcart.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>购物车</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <meta name="description" content="" />
    <link rel="stylesheet" href="lib/weui.min.css" />
    <link rel="stylesheet" href="css/jquery-weui.css" />
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body ontouchstart class="container">
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">购物车</div>
    </header>
    <div class="weui-content">
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <span>江苏蓝之蓝旗舰店</span
          ><a href="javascript:;" class="wy-dele"></a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-media-box_appmsg pd-10">
            <div class="weui-media-box__hd check-w weui-cells_checkbox">
              <label class="weui-check__label" for="cart-pto1">
                <div class="weui-cell__hd cat-check">
                  <input
                    type="checkbox"
                    class="weui-check"
                    name="cartpro"
                    id="cart-pto1"
                  /><i class="weui-icon-checked"></i>
                </div>
              </label>
            </div>
            <div class="weui-media-box__hd">
              <a href="../mall/templates/pro_info.html"
                ><img class="weui-media-box__thumb" src="upload/pro3.jpg" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="../mall/templates/pro_info.html" class="ord-pro-link"
                  >蓝之蓝蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食酒2瓶装包邮</a
                >
              </h1>
              <p class="weui-media-box__desc">
                规格：<span>红色</span>，<span>23</span>
              </p>
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">296.00</em>
                </div>
                <div class="pro-amount fr"><div class="Spinner"></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <span>江苏蓝之蓝旗舰店</span
          ><a href="javascript:;" class="wy-dele"></a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-media-box_appmsg pd-10">
            <div class="weui-media-box__hd check-w weui-cells_checkbox">
              <label class="weui-check__label" for="cart-pto2">
                <div class="weui-cell__hd cat-check">
                  <input
                    type="checkbox"
                    class="weui-check"
                    name="cartpro"
                    id="cart-pto2"
                  /><i class="weui-icon-checked"></i>
                </div>
              </label>
            </div>
            <div class="weui-media-box__hd">
              <a href="../mall/templates/pro_info.html"
                ><img class="weui-media-box__thumb" src="upload/pro3.jpg" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="../mall/templates/pro_info.html" class="ord-pro-link"
                  >蓝之蓝蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食酒2瓶装包邮</a
                >
              </h1>
              <p class="weui-media-box__desc">
                规格：<span>红色</span>，<span>23</span>
              </p>
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">296.00</em>
                </div>
                <div class="pro-amount fr"><div class="Spinner"></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <span>江苏蓝之蓝旗舰店</span
          ><a href="javascript:;" class="wy-dele"></a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-media-box_appmsg pd-10">
            <div class="weui-media-box__hd check-w weui-cells_checkbox">
              <label class="weui-check__label" for="cart-pto3">
                <div class="weui-cell__hd cat-check">
                  <input
                    type="checkbox"
                    class="weui-check"
                    name="cartpro"
                    id="cart-pto3"
                  /><i class="weui-icon-checked"></i>
                </div>
              </label>
            </div>
            <div class="weui-media-box__hd">
              <a href="../mall/templates/pro_info.html"
                ><img class="weui-media-box__thumb" src="upload/pro3.jpg" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="../mall/templates/pro_info.html" class="ord-pro-link"
                  >蓝之蓝蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食酒2瓶装包邮</a
                >
              </h1>
              <p class="weui-media-box__desc">
                规格：<span>红色</span>，<span>23</span>
              </p>
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">296.00</em>
                </div>
                <div class="pro-amount fr"><div class="Spinner"></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <span>江苏蓝之蓝旗舰店</span
          ><a href="javascript:;" class="wy-dele"></a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-media-box_appmsg pd-10">
            <div class="weui-media-box__hd check-w weui-cells_checkbox">
              <label class="weui-check__label" for="cart-pto4">
                <div class="weui-cell__hd cat-check">
                  <input
                    type="checkbox"
                    class="weui-check"
                    name="cartpro"
                    id="cart-pto4"
                  /><i class="weui-icon-checked"></i>
                </div>
              </label>
            </div>
            <div class="weui-media-box__hd">
              <a href="../mall/templates/pro_info.html"
                ><img class="weui-media-box__thumb" src="upload/pro3.jpg" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="../mall/templates/pro_info.html" class="ord-pro-link"
                  >蓝之蓝蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食酒2瓶装包邮</a
                >
              </h1>
              <p class="weui-media-box__desc">
                规格：<span>红色</span>，<span>23</span>
              </p>
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">296.00</em>
                </div>
                <div class="pro-amount fr"><div class="Spinner"></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--底部导航-->
    <div class="foot-black"></div>
    <div class="weui-tabbar wy-foot-menu">
      <div class="npd cart-foot-check-item weui-cells_checkbox allselect">
        <label class="weui-cell allsec-well weui-check__label" for="all">
          <div class="weui-cell__hd">
            <input type="checkbox" class="weui-check" name="all-sec" id="all" />
            <i class="weui-icon-checked"></i>
          </div>
          <div class="weui-cell__bd">
            <p class="font-14">全选</p>
          </div>
        </label>
      </div>
      <div class="weui-tabbar__item  npd">
        <p class="cart-total-txt">
          合计：<i>￥</i><em class="num font-16" id="zong1">22222.00</em>
        </p>
      </div>
      <a href="../../mine/templates/order_info.html" class="red-color npd w-90 t-c">
        <p class="promotion-foot-menu-label">去结算</p>
      </a>
    </div>

    <script src="lib/jquery-2.1.4.js"></script>
    <script src="lib/fastclick.js"></script>
    <script type="text/javascript" src="js/jquery.Spinner.js"></script>
    <script>
      $(function() {
        FastClick.attach(document.body);
      });
    </script>
    <script type="text/javascript">
      $(function() {
        $('.Spinner').Spinner({ value: 1, len: 3, max: 999 });
      });
    </script>
    <script src="js/jquery-weui.js"></script>
    <!---全选按钮-->

    <script type="text/javascript">
      $(document).ready(function() {
        $('.allselect').click(function() {
          if (
            $(this)
              .find('input[name=all-sec]')
              .prop('checked')
          ) {
            $('input[name=cartpro]').each(function() {
              $(this).prop('checked', true);
            });
          } else {
            $('input[name=cartpro]').each(function() {
              if ($(this).prop('checked')) {
                $(this).prop('checked', false);
              } else {
                $(this).prop('checked', true);
              }
            });
          }
        });
      });
    </script>
    <script>
      $(document).on('click', '.wy-dele', function() {
        $.confirm(
          '您确定要把此商品从购物车删除吗?',
          '确认删除?',
          function() {
            $.toast('文件已经删除!');
          },
          function() {
            //取消操作
          }
        );
      });
    </script>
  </body>
</html>