accounts/urls.py
from django.conf.urls import url

from accounts import views

urlpatterns = [
    # 用户登录
    url(r'^user/login/$', views.user_login, name='user_login'),
    # 用户退出
    url(r'^user/logout/$', views.user_logout, name='user_logout'),
    # 用户注册
    url(r'^user/register/$', views.user_register, name='user_register'),

    # 地址列表
    url(r'^user/address/list/$', views.address_list, name='address_list'),
    # 地址的修改和编辑
    # user/address/edit/add/   user/address/edit/12/
    url(r'^user/address/edit/(?P<pk>\S+)/$', views.address_edit, name='address_edit'),
    url(r'^user/address/delete/(?P<pk>\d+)/$', views.address_delete, name='address_delete'),

]

django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # django自带的后台管理
    url(r'^admin/', admin.site.urls),
    # xadmin的配置
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # 商品部分
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # 用户账户模块
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # 系统模块
    url(r'^sys/', include('system.urls', namespace='system')),
    # 个人中心
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

mine/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from mine import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # 订单详情
    url(r'^order/detail/(?P<sn>\S+)/$', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    # 添加到购物车
    url(r'^cart/add/(?P<prod_uid>\S+)/$', views.cart_add, name='cart_add'),
    # 我的购物车
    url(r'^cart/$', views.cart, name='cart'),
    # 提交订单
    url(r'^order/pay/$', views.order_pay, name='order_pay'),
    # 我的订单列表
    url(r'^order/list/$', login_required(views.OrderListView.as_view()), name='order_list'),
    # 我的收藏
    url(r'^prod/collect/$', views.prod_collect, name='prod_collect'),
]

mine/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from accounts.models import User
from mall.models import Product
from system.models import ImageFile
from utils import constants

"""
购物流程
1. 查看商品
2. 加入购物车
3. 选择购物车中的商品下订单（选择收货地址，是否开发票）
4. 支付
5. 确认收货
"""


class Order(models.Model):
    """ 订单模型 """
    sn = models.CharField('订单编号', max_length=32)
    user = models.ForeignKey(User, related_name='orders')
    buy_count = models.IntegerField('购买数量', default=1)
    buy_amount = models.FloatField('总价')

    to_user = models.CharField('收货人', max_length=32)
    to_area = models.CharField('省市区', max_length=32)
    to_address = models.CharField('详细地址', max_length=256)
    to_phone = models.CharField('手机号码', max_length=32)

    remark = models.CharField('备注', max_length=255, null=True, blank=True)

    # 快递信息
    express_type = models.CharField('快递', max_length=32, null=True, blank=True)
    express_no = models.CharField('单号', max_length=32, null=True, blank=True)

    status = models.SmallIntegerField('订单状态',
                                      choices=constants.ORDER_STATUS_CHOICES,
                                      default=constants.ORDER_STATUS_SUBMIT)

    class Meta:
        db_table = 'mine_order'
        verbose_name = '订单管理'
        verbose_name_plural = '订单管理'

    def get_cart_products(self):
        """ 购物车中 已下单的商品 """
        # 排除还在购物车状态的商品
        return self.carts.exclude(status=constants.ORDER_STATUS_INIT)


class Cart(models.Model):
    """ 购物车 """
    user = models.ForeignKey(User, related_name='carts')
    product = models.ForeignKey(Product)
    order = models.ForeignKey(Order, verbose_name='订单', related_name='carts', null=True)
    # 商品快照
    name = models.CharField('商品名称', max_length=128)
    img = models.ImageField('商品的主图')
    price = models.IntegerField('兑换价格')
    origin_price = models.FloatField('原价')

    count = models.PositiveIntegerField('购买数量')
    amount = models.FloatField('总额')

    status = models.SmallIntegerField('状态',
                                      choices=constants.ORDER_STATUS_CHOICES,
                                      default=constants.ORDER_STATUS_INIT)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'mine_cart'
        verbose_name = '购物车'
        verbose_name_plural = '购物车'


class Comments(models.Model):
    """ 商品评价 """
    # 评分的维度
    # 匿名
    # 置顶，排序
    # 评论内容
    # 关联图片
    product = models.ForeignKey(Product, related_name='comments', verbose_name='商品')
    user = models.ForeignKey(User, related_name='comments', verbose_name='用户')
    order = models.ForeignKey(Order, related_name='comments', verbose_name='订单')
    desc = models.CharField('评价内容', max_length=256)
    reorder = models.SmallIntegerField('排序', default=0)
    is_anonymous = models.BooleanField('是否匿名', default=True)

    score = models.FloatField('商品评分', default=10.0)
    score_deliver = models.FloatField('配送服务分', default=10.0)
    score_package = models.FloatField('快递包装分', default=10.0)
    score_speed = models.FloatField('送货速度分', default=10.0)

    is_valid = models.BooleanField('是否有效', default=True)
    img_list = GenericRelation(ImageFile,
                               verbose_name='评价晒图',
                               related_query_name="img_list")

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('最后更新时间', auto_now=True)

    class Meta:
        db_table = 'mine_product_comments'
        verbose_name = '商品评价'
        verbose_name_plural = '商品评价'

mine/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum, Q
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView

from mall.models import Product
from mine.models import Order, Cart
from utils import constants, tools


@login_required
def index(request):
    """ 个人中心首页 """
    return render(request, 'mine.html', {
        'constants': constants
    })


class OrderDetailView(DetailView):
    """ 订单详情 """
    model = Order
    slug_field = 'sn'
    slug_url_kwarg = 'sn'
    template_name = 'order_info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['constants'] = constants
        return context


@login_required
@transaction.atomic()
def cart_add(request, prod_uid):
    """ 添加商品到购物车 写接口 """
    user = request.user
    product = get_object_or_404(Product, uid=prod_uid,
                                is_valid=True,
                                status=constants.PRODUCT_STATUS_SELL)
    # 购买数量
    count = int(request.POST.get('count', 1))
    # 校验库存
    if product.ramain_count < count:
        return HttpResponse('no')
    # 减库存
    product.update_store_count(count)
    # 生成购物车记录
    # 如果已经添加到购物车了，就把的购买数量和价格更新一下
    try:
        cart = Cart.objects.get(product=product, user=user,
                                status=constants.ORDER_STATUS_INIT)
        # 更新价格和数量
        count = cart.count + count
        cart.count = count
        cart.amount = count * cart.price
        cart.save()
    except Cart.DoesNotExist:
        # 没有加入到过购物车
        Cart.objects.create(
            product=product,
            user=user,
            name=product.name,
            img=product.img,
            price=product.price,
            origin_price=product.origin_price,
            count=count,
            amount=count * product.price
        )
    return HttpResponse('ok')


@login_required
def cart(request):
    """ 我的购物车 """
    user = request.user
    # 我购物车中的商品列表
    prod_list = user.carts.filter(status=constants.ORDER_STATUS_INIT)
    # 聚合查询
    if request.method == 'POST':
        # 提交订单
        # 1. 保存用户的地址快照
        default_addr = user.default_addr
        if not default_addr:
            # 消息通知
            messages.warning(request, '请选择地址信息')
            return redirect('accounts:address_list')
        # 订单总额计算
        cart_total = prod_list.aggregate(sum_amount=Sum('amount'),
                                         sum_count=Sum('count'))
        order = Order.objects.create(
            user=user,
            sn=tools.gen_trans_id(),
            buy_amount=cart_total['sum_amount'],
            buy_count=cart_total['sum_count'],
            to_user=default_addr.username,
            to_area=default_addr.get_region_format(),
            to_address=default_addr.address,
            to_phone=default_addr.phone
        )
        # 2. 修改购物车中的状态 已提交
        # 3. 生成订单，关联到购物车
        prod_list.update(
            status=constants.ORDER_STATUS_SUBMIT,
            order=order
        )
        # 4. 跳转到订单详情
        messages.success(request, '下单成功，请支付')
        return redirect('mine:order_detail', order.sn)

    return render(request, 'cart.html', {
        'prod_list': prod_list
    })


@login_required
def order_pay(request):
    """ 提交订单 """
    user = request.user
    if request.method == 'POST':
        sn = request.POST.get('sn', None)
        # 1. 查询订单信息
        order = get_object_or_404(Order, sn=sn, user=user,
                                  status=constants.ORDER_STATUS_SUBMIT)
        # 2. 验证钱够不够
        if order.buy_amount > user.integral:
            messages.error(request, '积分余额不足')
            return redirect('mine:order_detail', sn=sn)
        # 3. 钱扣掉
        user.ope_integral_account(0, order.buy_amount)
        # 4. 修改订单状态
        order.status = constants.ORDER_STATUS_PAIED
        order.save()
        # 5. 修改购物车关联的状态
        order.carts.all().update(status=constants.ORDER_STATUS_PAIED)
        messages.success(request, '支付成功')
    return redirect('mine:order_detail', sn=sn)


@login_required
def order_list(request):
    """ 我的订单列表 """
    status = request.GET.get('status', '')
    try:
        status = int(status)
    except ValueError:
        status = ''
    # 1. 查询订单数据
    # 2. 分页处理
    return render(request, 'order_list.html', {
        'constants': constants,
        'status': status
    })


# class-based
class OrderListView(ListView):
    """ 基于类视图的订单列表 """
    model = Order
    template_name = 'order_list.html'

    def get_queryset(self):
        """ 查询订单 """
        status = self.request.GET.get('status', '')
        user = self.request.user
        query = Q(user=user)
        if status:
            query = query & Q(status=status)
        return Order.objects.filter(query).exclude(
            status=constants.ORDER_STATUS_DELETED
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status = self.request.GET.get('status', '')
        try:
            status = int(status)
        except ValueError:
            status = ''
        context['constants'] = constants
        context['status'] = status
        return context



@login_required
def prod_collect(request):
    """ 我的收藏 """
    return render(request, 'prod_collect.html')

mine/templates/cart.html
{% extends 'base.html' %}
{% block title %}
    <title>购物车</title>
{% endblock %}
{% block container %}
    <form action="." method="post">
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">购物车</div>
    </header>
    <div class="weui-content" method="post">
      {% for item in prod_list %}
       {% with product=item.product %}
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <span>官方自营</span
          ><a href="javascript:;" class="wy-dele"></a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-media-box_appmsg pd-10">
            <div class="weui-media-box__hd check-w weui-cells_checkbox">
              <label class="weui-check__label" for="cart-pto1">
                <div class="weui-cell__hd cat-check">
                  <input
                    type="checkbox"
                    class="weui-check"
                    name="cartpro"
                    id="cart-pto1"
                  /><i class="weui-icon-checked"></i>
                </div>
              </label>
            </div>
            <div class="weui-media-box__hd">
              <a href="{% url 'mall:product_detail' product.uid %}"
                ><img class="weui-media-box__thumb" src="{{ item.img.url }}" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="{% url 'mall:product_detail' product.uid %}" class="ord-pro-link"
                  >{{ item.name }}</a
                >
              </h1>
{#              <p class="weui-media-box__desc">#}
{#                规格：<span>红色</span>，<span>23</span>#}
{#              </p>#}
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">{{ item.price }}</em>
                </div>
                <div class="pro-amount fr"><div class="Spinner" data-value="{{ item.count }}"></div></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    <!--底部导航-->
    <div class="foot-black"></div>
    <div class="weui-tabbar wy-foot-menu">
      <div class="npd cart-foot-check-item weui-cells_checkbox allselect">
        <label class="weui-cell allsec-well weui-check__label" for="all">
          <div class="weui-cell__hd">
            <input type="checkbox" class="weui-check" name="all-sec" id="all" />
            <i class="weui-icon-checked"></i>
          </div>
          <div class="weui-cell__bd">
            <p class="font-14">全选</p>
          </div>
        </label>
      </div>
      <div class="weui-tabbar__item  npd">
        <p class="cart-total-txt">
          合计：<i>￥</i>
            {% if cart_total is not None %}
            <em class="num font-16" id="zong1">{{ cart_total.sum_amount }}</em>
            {% else %}
            <em class="num font-16" id="zong1">0</em>
            {% endif %}
        </p>
      </div>
      <button type="submit" class="red-color npd w-90 t-c">
        <p class="promotion-foot-menu-label">去结算</p>
      </button>
    </div>
</form>
{% endblock %}
{% block footer %}
    <script type="text/javascript" src="/static/js/jquery.Spinner.js"></script>
    <script type="text/javascript">
      $(function() {
        $('.Spinner').Spinner({ value: $('.Spinner').attr('data-value'), len: 3, max: 999 });
      });
    </script>
    <!---全选按钮-->

    <script type="text/javascript">
      $(document).ready(function() {
        $('.allselect').click(function() {
          if (
            $(this)
              .find('input[name=all-sec]')
              .prop('checked')
          ) {
            $('input[name=cartpro]').each(function() {
              $(this).prop('checked', true);
            });
          } else {
            $('input[name=cartpro]').each(function() {
              if ($(this).prop('checked')) {
                $(this).prop('checked', false);
              } else {
                $(this).prop('checked', true);
              }
            });
          }
        });
      });
    </script>
    <script>
      $(document).on('click', '.wy-dele', function() {
        $.confirm(
          '您确定要把此商品从购物车删除吗?',
          '确认删除?',
          function() {
            $.toast('文件已经删除!');
          },
          function() {
            //取消操作
          }
        );
      });
    </script>
{% endblock %}

mine/templates/mine.html
{% extends 'base.html' %}
{% block title %}
    <title>会员中心</title>
{% endblock %}
{% block container %}
    <!--主体-->
    <div class="weui-content">
      <div class="wy-center-top">
        <div class="weui-media-box weui-media-box_appmsg">
          <div class="weui-media-box__hd">
            <img
              class="weui-media-box__thumb radius"
              src="upload/headimg.jpg"
              alt=""
            />
          </div>
          <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title user-name">张三</h4>
            <p class="user-grade">等级：普通会员</p>
            <p class="user-integral">
              剩余积分：<em class="num">500.0</em>积分
            </p>
          </div>
        </div>
      </div>
      <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">
          <a
            href="{% url 'mine:order_list' %}"
            class="weui-cell weui-cell_access center-alloder"
          >
            <div class="weui-cell__bd wy-cell">
              <div class="weui-cell__hd">
                <img
                  src="/static/images/center-icon-order-all.png"
                  alt=""
                  class="center-list-icon"
                />
              </div>
              <div class="weui-cell__bd weui-cell_primary">
                <p class="center-list-txt">全部订单</p>
              </div>
            </div>
            <span class="weui-cell__ft"></span>
          </a>
        </div>
        <div class="weui-panel__bd">
          <div class="weui-flex">
            <div class="weui-flex__item">
              <a href="{% url 'mine:order_list' %}?status={{ constants.ORDER_STATUS_SUBMIT }}" class="center-ordersModule">
                <span
                  class="weui-badge"
                  style="position: absolute;top:5px;right:10px; font-size:10px;"
                  >2</span
                >
                <div class="imgicon">
                  <img src="/static/images/center-icon-order-dfk.png" />
                </div>
                <div class="name">待付款</div>
              </a>
            </div>
            <div class="weui-flex__item">
              <a href="{% url 'mine:order_list' %}?status={{ constants.ORDER_STATUS_PAIED }}" class="center-ordersModule">
                <span
                  class="weui-badge"
                  style="position: absolute;top:5px;right:10px; font-size:10px;"
                  >1</span
                >
                <div class="imgicon">
                  <img src="/static/images/center-icon-order-dfh.png" />
                </div>
                <div class="name">待发货</div>
              </a>
            </div>
            <div class="weui-flex__item">
              <a href="{% url 'mine:order_list' %}?status={{ constants.ORDER_STATUS_SENT }}" class="center-ordersModule">
                <div class="imgicon">
                  <img src="/static/images/center-icon-order-dsh.png" />
                </div>
                <div class="name">待收货</div>
              </a>
            </div>
            <div class="weui-flex__item">
              <a href="{% url 'mine:order_list' %}?status={{ constants.ORDER_STATUS_DONE }}" class="center-ordersModule">
                <span
                  class="weui-badge"
                  style="position: absolute;top:5px;right:10px; font-size:10px;"
                  >2</span
                >
                <div class="imgicon">
                  <img src="/static/images/center-icon-order-dpj.png" />
                </div>
                <div class="name">待评价</div>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="weui-panel">
        <div class="weui-panel__bd">
          <div class="weui-media-box weui-media-box_small-appmsg">
            <div class="weui-cells">
              <a class="weui-cell weui-cell_access"
                 href="{% url 'mine:prod_collect' %}">
                <div class="weui-cell__hd">
                  <img
                    src="images/center-icon-sc.png"
                    alt=""
                    class="center-list-icon"
                  />
                </div>
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="center-list-txt">我的收藏</p>
                </div>
                <span class="weui-cell__ft"></span>
              </a>
              <a class="weui-cell weui-cell_access"
                 href="{% url 'accounts:address_list' %}">
                <div class="weui-cell__hd">
                  <img
                    src="/static/images/center-icon-dz.png"
                    alt=""
                    class="center-list-icon"
                  />
                </div>
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="center-list-txt">地址管理</p>
                </div>
                <span class="weui-cell__ft"></span>
              </a>
{#              <a class="weui-cell weui-cell_access" #}
{#                 href="../accounts/templates/pwd_change.html">#}
{#                <div class="weui-cell__hd">#}
{#                  <img#}
{#                    src="/static/images/center-icon-dlmm.png"#}
{#                    alt=""#}
{#                    class="center-list-icon"#}
{#                  />#}
{#                </div>#}
{#                <div class="weui-cell__bd weui-cell_primary">#}
{#                  <p class="center-list-txt">密码修改</p>#}
{#                </div>#}
{#                <span class="weui-cell__ft"></span>#}
{#              </a>#}
              <a class="weui-cell weui-cell_access"
                 href="{% url 'accounts:user_logout' %}">
                <div class="weui-cell__hd">
                  <img
                    src="/static/images/center-icon-out.png"
                    alt=""
                    class="center-list-icon"
                  />
                </div>
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="center-list-txt">退出账号</p>
                </div>
                <span class="weui-cell__ft"></span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--底部导航-->
    {% include 'footer.html' with tab='mine' %}
{% endblock %}

mine/templates/order_info.html
{% extends 'base.html' %}
{% block title %}
    <title>订单结算</title>
{% endblock %}
{% block container %}
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">订单详情</div>
    </header>
    <form class="weui-content" method="post"
        action="{% url 'mine:order_pay' %}">
        <input type="hidden" name="sn" value="{{ object.sn }}">
      <div class="wy-media-box weui-media-box_text address-select">
        <div class="weui-media-box_appmsg">
          <div class="weui-media-box__hd proinfo-txt-l" style="width:20px;">
            <span class="promotion-label-tit"
              ><img src="images/icon_nav_city.png"
            /></span>
          </div>
          <div class="weui-media-box__bd">
            <a href="{% url 'accounts:address_list' %}" class="weui-cell_access">
              <h4 class="address-name">

                <span>{{ object.to_user }}</span><span>{{ object.to_phone }}</span>
              </h4>
              <div class="address-txt"> {{ object.to_area }}{{ object.to_address }}</div>
            </a>
          </div>
          <div class="weui-media-box__hd proinfo-txt-l" style="width:16px;">
            <div class="weui-cell_access">
              <span class="weui-cell__ft"></span>
            </div>
          </div>
        </div>
      </div>
      <div class="wy-media-box weui-media-box_text">
        <div class="weui-media-box__bd">
          {% for item in object.get_cart_products %}
           {% with product=item.product  %}
          <div class="weui-media-box_appmsg ord-pro-list">
            <div class="weui-media-box__hd">
              <a href="{% url 'mall:product_detail' product.uid %}"
                ><img class="weui-media-box__thumb" src="{{ product.img.url }}" alt=""
              /></a>
            </div>
            <div class="weui-media-box__bd">
              <h1 class="weui-media-box__desc">
                <a href="{% url 'mall:product_detail' product.uid %}" class="ord-pro-link"
                  >{{ product.name }}</a
                >
              </h1>
{#              <p class="weui-media-box__desc">#}
{#                规格：<span>红色</span>，<span>23</span>#}
{#              </p>#}
              <div class="clear mg-t-10">
                <div class="wy-pro-pri fl">
                  ¥<em class="num font-15">{{ item.amount }}</em>
                </div>
                <div class="pro-amount fr">
                  <span class="font-13">数量×<em class="name">{{ item.count }}</em></span>
                </div>
              </div>
            </div>
          </div>
          {% endwith %}
          {%  endfor %}
        </div>
      </div>
      <div class="weui-panel">
        <div class="weui-panel__bd">
          <div class="weui-media-box weui-media-box_small-appmsg">
            <div class="weui-cells">
              <div class="weui-cell weui-cell_access">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14">
                    <span class="mg-r-10">配送方式</span
                    ><span class="fr">快递</span>
                  </p>
                </div>
              </div>
              <div class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14">
                    <span class="mg-r-10">运费</span
                    ><span class="fr txt-color-red"
                      >￥<em class="num">10.00</em></span
                    >
                  </p>
                </div>
              </div>
              <a class="weui-cell weui-cell_access" href="money.html">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14">
                    <span class="mg-r-10">可用积分</span
                    ><span class="sitem-tip"><em class="num">{{ user.integral }}</em>分</span>
                  </p>
                </div>
                <span class="weui-cell__ft"></span>
              </a>
              <a class="weui-cell weui-cell_access" href="coupon.html">
                <div class="weui-cell__bd weui-cell_primary">
                  <p class="font-14">
                    <span class="mg-r-10">优惠券</span
                    ><span class="sitem-tip"><em class="num">0</em>张可用</span>
                  </p>
                </div>
                <span class="weui-cell__ft"></span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="wy-media-box weui-media-box_text">
        <div class="mg10-0 t-c">
          总金额：<span class="wy-pro-pri mg-tb-5"
            >¥<em class="num font-20">{{ object.buy_amount }}</em></span
          >
        </div>
        {% if object.status == constants.ORDER_STATUS_PAIED %}
        <div class="mg10-0">
          <div class="weui-btn weui-btn_primary" >您已支付</div>
        </div>
          {% else %}
        <div class="mg10-0">
          <input class="weui-btn weui-btn_primary" type="submit">积分支付</input>
        </div>
          {% endif %}
      </div>
    </form>
{% endblock %}
{% block footer %}
    <script type="text/javascript" src="/static/js/jquery.Spinner.js"></script>
    <script type="text/javascript">
      $(function() {
        $('.Spinner').Spinner({ value: 1, len: 3, max: 999 });
      });
    </script>
    <script src="js/jquery-weui.js"></script>
{% endblock %}