accounts/urls.py
from django.conf.urls import url

from accounts import views

urlpatterns = [
    # 用户登录
    url(r'^user/login/$', views.user_login, name='user_login'),
    # 用户退出
    url(r'^user/logout/$', views.user_logout, name='user_logout'),
    # 用户注册
    url(r'^user/register/$', views.user_register, name='user_register'),

    # 地址列表
    url(r'^user/address/list/$', views.address_list, name='address_list'),
    # 地址的修改和编辑
    # user/address/edit/add/   user/address/edit/12/
    url(r'^user/address/edit/(?P<pk>\S+)/$', views.address_edit, name='address_edit'),
    url(r'^user/address/delete/(?P<pk>\d+)/$', views.address_delete, name='address_delete'),

]

django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # django自带的后台管理
    url(r'^admin/', admin.site.urls),
    # xadmin的配置
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # 商品部分
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # 用户账户模块
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # 系统模块
    url(r'^sys/', include('system.urls', namespace='system')),
    # 个人中心
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import F


class User(AbstractUser):
    """ 用户的基础信息表 """
    # username = models.CharField('用户名', max_length=64)
    # password = models.CharField('密码', max_length=255)
    avatar = models.ImageField('用户头像', upload_to='avatar', null=True, blank=True)
    integral = models.IntegerField('用户的积分', default=0)
    nickname = models.CharField('昵称', max_length=32)
    level = models.SmallIntegerField('用户级别')

    class Meta:
        db_table = 'accounts_user'
        verbose_name = '用户基础信息'
        verbose_name_plural = '用户基础信息'

    @property
    def default_addr(self):
        """ 用户的默认地址， 在多个地方用到 """
        addr = None
        user_list = self.user_address.filter(is_valid=True)
        # UserAddress.objects.filter(user=user, is_valid=True)
        # 1. 找到默认地址
        try:
            addr = user_list.filter(is_default=True)[0]
        except IndexError:
            try:
                addr = user_list[0]
                # 2. 如果没有默认地址，显示所有地址的第一个
            except IndexError:
                pass
        return addr

    def ope_integral_account(self, types, count):
        """ 积分操作 """
        if types == 1:
            # 充值
            self.integral = F('integral') + abs(count)
        else:
            # 消费
            self.integral = F('integral') - abs(count)
        self.save()
        self.refresh_from_db()

    def __str__(self):
        return self.username


class UserProfile(models.Model):
    """ 用户的详细信息 """
    SEX_CHOICES = (
        (1, '男'),
        (0, '女'),
    )
    user = models.OneToOneField(User)
    real_name = models.CharField('真实姓名', max_length=32)
    email = models.CharField('电子邮箱', max_length=128, null=True, blank=True)
    is_email_valid = models.BooleanField('邮箱是否已经验证', default=False)
    phone_no = models.CharField('手机号码', max_length=20, null=True, blank=True)
    is_phone_valid = models.BooleanField('是否已经验证', default=False)
    sex = models.SmallIntegerField('性别', default=1, choices=SEX_CHOICES)
    age = models.SmallIntegerField('年龄', default=0)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'accounts_user_profile'
        verbose_name = '用户详细信息'
        verbose_name_plural = '用户详细信息'


class UserAddress(models.Model):
    """ 用户的地址信息 """
    user = models.ForeignKey(User, related_name='user_address')
    province = models.CharField('省份', max_length=32)
    city = models.CharField('市区', max_length=32)
    area = models.CharField('区域', max_length=32)
    town = models.CharField('街道', max_length=32, null=True, blank=True)

    address = models.CharField('详细地址', max_length=64)
    username = models.CharField('收件人', max_length=32)
    phone = models.CharField('收件人的电话', max_length=32)

    is_default = models.BooleanField('是否为默认地址', default=False)
    is_valid = models.BooleanField('是否有效', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'accounts_user_address'
        verbose_name = '用户地址'
        verbose_name_plural = '用户地址'
        ordering = ['is_default', '-updated_at']

    def get_phone_format(self):
        """ 格式化手机号码显示 """
        return self.phone[0:3] + '****' + self.phone[7:]

    def get_region_format(self):
        """ 省市区 """
        return '{self.province} {self.city} {self.area}'.format(self=self)

    def __str__(self):
        return self.get_region_format() + self.address


class LoginRecord(models.Model):
    """ 用户的登录历史 """
    user = models.ForeignKey(User)
    username = models.CharField('登录的账号', max_length=64)
    ip = models.CharField('IP', max_length=32)
    address = models.CharField('地址', max_length=32, null=True, blank=True)
    source = models.CharField('登录的来源', max_length=32)

    created_at = models.DateTimeField('登录时间')

    class Meta:
        db_table = 'accounts_login_record'
        verbose_name = '登录历史'
        verbose_name_plural = '登录历史'


class PasswdChangeLog(models.Model):
    """ 用户的密码修改历史 """
    pass

accounts/forms.py
import re

from django import forms
from django.contrib.auth import authenticate, login

from accounts.models import User, UserAddress
from utils.verify import VerifyCode


class UserLoginForm(forms.Form):
    """ 用户登录表单 """
    username = forms.CharField(label='用户名', max_length=64)
    password = forms.CharField(label='密码', max_length=64,
                               widget=forms.PasswordInput,
                               error_messages={
                                   'required': '请输入密码'
                               })
    verify_code = forms.CharField(label='验证码', max_length=4)

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    # def clean_username(self):
    #     """ 验证用户名 hook 钩子函数"""
    #     username = self.cleaned_data['username']
    #     print(username)
    #     # 判断用户名是否为手机号码
    #     pattern = r'^0{0,1}1[0-9]{10}$'
    #     if not re.search(pattern, username):
    #         raise forms.ValidationError('请输入正确的手机号码')
    #     return username

    def clean_verify_code(self):
        """ 验证用户输入的验证码是否正确 """
        verify_code = self.cleaned_data['verify_code']
        if not verify_code:
            raise forms.ValidationError('请输入验证码')
        client = VerifyCode(self.request)
        if not client.validate_code(verify_code):
            raise forms.ValidationError('您输入的验证码不正确')
        return verify_code

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        # 获取用户名和密码 ，不建议使用[]的方式
        # username = cleaned_data['username']

        username = cleaned_data.get('username', None)
        password = cleaned_data.get('password', None)
        if username and password:
            # 查询用户名和密码匹配的用户
            user_list = User.objects.filter(username=username)
            if user_list.count() == 0:
                raise forms.ValidationError('用户名不存在')
            # # 验证密码是否正确
            # if not user_list.filter(password=password).exists():
            #     raise forms.ValidationError('密码错误')
            if not authenticate(username=username, password=password):
                raise forms.ValidationError('密码错误')
        return cleaned_data


class UserRegistForm(forms.Form):
    """ 用户注册表单 """
    username = forms.CharField(label='用户名', max_length=64)
    nickname = forms.CharField(label='昵称', max_length=64)
    password = forms.CharField(label='密码', max_length=64, widget=forms.PasswordInput)
    password_repeat = forms.CharField(label='重复密码', max_length=64, widget=forms.PasswordInput)
    verify_code = forms.CharField(label='验证码', max_length=4)

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_username(self):
        """ 验证用户名是否已经被注册 """
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise forms.ValidationError('用户名已存在')
        return data

    def clean_verify_code(self):
        """ 验证用户输入的验证码是否正确 """
        verify_code = self.cleaned_data['verify_code']
        if not verify_code:
            raise forms.ValidationError('请输入验证码')
        client = VerifyCode(self.request)
        if not client.validate_code(verify_code):
            raise forms.ValidationError('您输入的验证码不正确')
        return verify_code

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password', None)
        password_repeat = cleaned_data.get('password_repeat', None)
        if password and password_repeat:
            if password != password_repeat:
                raise forms.ValidationError('两次密码输入不一致')
        return cleaned_data

    def register(self):
        """ 注册方法 """
        data = self.cleaned_data
        # 1. 创建用户
        User.objects.create_user(username=data['username'],
                                 password=data['password'],
                                 level=0,
                                 nickname='昵称')
        # 2. 自动登录
        user = authenticate(username=data['username'],
                     password=data['password'])
        login(self.request, user)
        return user


class UserAddressForm(forms.ModelForm):
    """" 地址新增|修改 """

    region = forms.CharField(label='大区域选项', max_length=64, required=True,
                             error_messages={
                                 'required': '请选择地址'
                             })

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    class Meta:
        model = UserAddress
        fields = ['address', 'username', 'phone', 'is_default']
        widgets = {
            'is_default': forms.CheckboxInput(attrs={
                'class': 'weui-switch'
            })
        }

    def clean_phone(self):
        """ 验证用户输入的手机号码 """
        phone = self.cleaned_data['phone']
        # 判断用户名是否为手机号码
        pattern = r'^0{0,1}1[0-9]{10}$'
        if not re.search(pattern, phone):
            raise forms.ValidationError('请输入正确的手机号码')
        return phone

    def clean(self):
        cleaned_data = super().clean()
        # 查询当前登录用户的地址数据
        addr_list = UserAddress.objects.filter(is_valid=True, user=self.request.user)
        if addr_list.count() >= 20:
            raise forms.ValidationError('最多只能添加20个地址')
        return cleaned_data

    def save(self, commit=True):
        obj = super().save(commit=False)
        region = self.cleaned_data['region']
        # 省市区的数据
        (province, city, area) = region.split(' ')
        obj.province = province
        obj.city = city
        obj.area = area
        obj.user = self.request.user

        # 修改的时候，如果已经有了默认地址，当前也勾选了默认地址选项
        # 需要把之前的地址都改为非默认的地址
        if self.cleaned_data['is_default']:
            UserAddress.objects.filter(is_valid=True, user=self.request.user,
                                       is_default=True).update(is_default=False)
        obj.save()


accounts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout

from accounts.forms import UserLoginForm, UserRegistForm, UserAddressForm
from accounts.models import User, UserAddress
from utils import constants
from utils.verify import VerifyCode


def user_login(request):
    """ 用户登录 """
    # 如果登录是从其他页面跳转过来的，会带next参数，如果有next参数，登录完成后，需要调转到
    # next所对应的地址，否则，跳转到首页上去
    next_url = request.GET.get('next', 'index')
    # 第一次访问URL GET 展示表单，供用户输入
    # 第二次访问URL POST
    if request.method == 'POST':
        form = UserLoginForm(request=request, data=request.POST)
        print(request.POST)
        client = VerifyCode(request)
        code = request.POST.get('vcode', None)
        rest = client.validate_code(code)
        print('验证结果：', rest)
        # 表单是否通过了验证
        if form.is_valid():
            # 执行登录
            data = form.cleaned_data

            # ## 使用自定义的方式实现登录
            # # 查询用户信息 [MD5]加密算法，不可逆的加密算法 1243 -> sdfadfad
            # user = User.objects.get(username=data['username'], password=data['password'])
            # # 设置用户ID到session
            # request.session[constants.LOGIN_SESSION_ID] = user.id
            # # 登录后的跳转
            # return redirect('index')

            ### 使用django-auth来实现登录
            user = authenticate(request, username=data['username'], password=data['password'])
            if user is not None:
                login(request, user)
                request.session['user_id'] = user.id
                # 登录后的跳转
                return redirect(next_url)
        else:
            print(form.errors)
    else:
        form = UserLoginForm(request)
    return render(request, 'login.html', {
        'form': form,
        'next_url': next_url
    })


def user_logout(request):
    """ 用户退出登录 """
    logout(request)
    return redirect('index')


def user_register(request):
    """  用户注册 """
    if request.method == 'POST':
        form = UserRegistForm(request=request, data=request.POST)
        if form.is_valid():
            # 调用注册方法
            print('开始注册')
            form.register()
            print('注册成功')
            return redirect('index')
            # return HttpResponse('ok')
        else:
            print(form.errors)
    else:
        form = UserRegistForm(request=request)
    return render(request, 'register.html', {
        'form': form
    })


@login_required
def address_list(request):
    """ 地址列表 """
    my_addr_list = UserAddress.objects.filter(user=request.user, is_valid=True)
    return render(request, 'address_list.html', {
        'my_addr_list': my_addr_list
    })


@login_required
def address_edit(request, pk):
    """ 地址新增或者是编辑 """
    user = request.user
    addr = None
    initial = {}
    # 如果PK是数字，则表示修改
    if pk.isdigit():
        # 查询相关的地址信息
        addr = get_object_or_404(UserAddress, pk=pk, user=user, is_valid=True)
        initial['region'] = addr.get_region_format()
    if request.method == 'POST':
        form = UserAddressForm(request=request, data=request.POST,
                               initial=initial, instance=addr)
        if form.is_valid():
            form.save()
            return redirect('accounts:address_list')
    else:
        form = UserAddressForm(request=request, instance=addr, initial=initial)
    return render(request, 'address_edit.html', {
        'form': form
    })


def address_delete(request, pk):
    """ 删除地址 """
    addr = get_object_or_404(UserAddress, pk=pk, is_valid=True, user=request.user)
    addr.is_valid = False
    addr.save()
    return HttpResponse('ok')

accounts/templates/address_edit.html
{% extends 'base.html' %}
{% block title %}
<title>编辑地址</title>
{% endblock %}
{% block container %}
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">编辑地址</div>
    </header>
    <form class="weui-content" method="post" action=".">
      <div class="weui-cells weui-cells_form wy-address-edit">
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">收货人</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              name="username"
              type="text"
              value="{{ form.username.value|default_if_none:'' }}"
              placeholder="请输入收件人"
            />
          </div>
        </div>
          {{ form.username.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">手机号</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="text"
              name="phone"
              value="{{ form.phone.value|default_if_none:'' }}"
              placeholder="请输入手机号码"
            />
          </div>
        </div>
          {{ form.phone.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label for="name" class="weui-label wy-lab">所在地区</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              id="address"
              type="text"
              name="region"
              value="{{ form.region.value|default_if_none:'' }}"
              readonly=""
            />
          </div>
        </div>
          {{ form.region.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">详细地址</label>
          </div>
          <div class="weui-cell__bd">
            <textarea
              class="weui-textarea"
              name="address"
              placeholder="请输入详细地址"
            >{{ form.address.value|default_if_none:'' }}</textarea>
          </div>
        </div>
          {{ form.address.errors }}
          {{ form.non_field_errors }}
        <div class="weui-cell weui-cell_switch">
          <div class="weui-cell__bd">设为默认地址</div>
          <div class="weui-cell__ft">
              {{ form.is_default }}
          </div>
        </div>
      </div>
      <div class="weui-btn-area">
          <input class="weui-btn weui-btn_primary" type="submit" value="保存此地址">
        <a href="javascript:;" id="id_delete_addr" class="weui-btn weui-btn_warn">删除此地址</a>
      </div>
    </form>

{% endblock %}
{% block footer %}
<script src="/static/js/city-picker.js"></script>
<script>
  $('#address').cityPicker({
    title: '选择出发地',
    onChange: function(picker, values, displayValues) {
      console.log(values, displayValues);
    }
  });
  $("#id_delete_addr").click(function() {
      {# 弹框确认 #}
      if(window.confirm('确认删除该地址吗')){
          {# jquery ajax #}
          $.post("{% url 'accounts:address_delete' form.instance.id %}", function(rest) {
            if(rest === 'ok') {
                window.location.href = "{% url 'accounts:address_list' %}";
            }
          })
      }
  })
</script>
{% endblock %}

accounts/templates/address_list.html
{% extends 'base.html' %}
{% block title %}
<title>地址管理</title>
{% endblock %}
{% block container %}
<!--主体-->
<header class="wy-header">
  <div class="wy-header-icon-back"><span></span></div>
  <div class="wy-header-title">地址管理</div>
</header>
<div class="weui-content">
  <div class="weui-panel address-box">
    {% for item in my_addr_list %}
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_text address-list-box">
        <a href="{% url 'accounts:address_edit' item.id %}" class="address-edit"></a>
        <h4 class="weui-media-box__title">
            <span>{{ item.username }}</span>
            <span>{{ item.get_phone_format }}</span>
        </h4>
        <p class="weui-media-box__desc address-txt">
            {{ item.get_regin_format }}
            {{ item.address }}
        </p>
        {% if item.is_default %}
          <span class="default-add">默认地址</span>
        {% endif %}
      </div>
    </div>
    {% endfor %}

    
  </div>
  <div class="weui-btn-area">
    <a class="weui-btn weui-btn_primary"
       href="{% url 'accounts:address_edit' 'add' %}" id="showTooltips">添加收货地址</a>
  </div>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% block title %}
    <title>登陆</title>
    <style type="text/css">
    body {
        background:#323542;
    }
    </style>
{% endblock %}
{% block container %}
<!--主体-->
    <div class="login-box">
      <div class="lg-title">欢迎登陆积分商城</div>
      <div class="login-form">
        <form action="{% url 'accounts:user_login' %}?next={{ next_url }}" method="post">
          <div class="login-user-name common-div">
            <span class="eamil-icon common-icon">
              <img src="/static/images/eamil.png" />
            </span>
            <input
              type="text"
              name="username"
              value="{{ form.username.value|default_if_none:'' }}"
              placeholder="请输入您的手机号"
            />
          </div>
          {{ form.username.errors }}
          <div class="login-user-pasw common-div">
            <span class="pasw-icon common-icon">
              <img src="/static/images/password.png" />
            </span>
            <input
              type="password"
              name="password"
              value=""
              placeholder="请输入您的密码"
            />
          </div>
          {{ form.password.errors }}
          <!-- 验证码  -->
          <div class="login-user-vcode common-div">
           <div class="weui-cell__bd">
              <input
                  type="text"
                  name="verify_code"
                  value=""
                  placeholder="请输入您的密码"
                />
            </div>
            <div class="weui-cell__ft">
                <img class="verify-code-img"
                     style="width: 100%; height: 100%;"
                     src="{% url 'system:verify_code' %}"
                     data-src="{% url 'system:verify_code' %}" alt="验证码">
            </div>
          </div>
          {{ form.verify_code.errors }}
          {{ form.non_field_errors }}
          <button class="login-btn common-div" type="submit">登录</button>
          <a href="javascript:;" class="login-oth-btn common-div">微信登陆</a>
          <a href="javascript:;" class="login-oth-btn common-div">QQ登陆</a>
        </form>
      </div>
      <div class="forgets">
        <a href="pwd_change.html">忘记密码？</a>
        <a href="{% url 'accounts:user_register' %}">免费注册</a>
      </div>
    </div>
{% endblock %}
{% block footer %}
    <script>
        $('.verify-code-img').click(function() {
            $(this).attr('src', $(this).attr('data-src') + '?t=' + new Date().getTime())
        })
    </script>
{% endblock %}

accounts/templates/pwd_change.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>密码修改</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <meta name="description" content="" />
    <link rel="stylesheet" href="lib/weui.min.css" />
    <link rel="stylesheet" href="css/jquery-weui.css" />
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body ontouchstart class="container">
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">密码修改</div>
    </header>
    <div class="weui-content">
      <div class="weui-cells weui-cells_form wy-address-edit">
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">新密码</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="number"
              pattern="[0-9]*"
              placeholder="请输入新密码"
            />
          </div>
        </div>
        <div class="weui-cell weui-cell_vcode">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">手机号</label>
          </div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="tel" placeholder="请输入手机号" />
          </div>
          <div class="weui-cell__ft">
            <button class="weui-vcode-btn">获取验证码</button>
          </div>
        </div>
        <div class="weui-cell weui-cell_vcode">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">验证码</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="number"
              placeholder="请输入验证码"
            />
          </div>
          <div class="weui-cell__ft">
            <img class="weui-vcode-img" src="./images/vcode.jpg" />
          </div>
        </div>
      </div>
      <div class="weui-btn-area">
        <a href="javascript:;" class="weui-btn weui-btn_primary">确认修改</a>
      </div>
    </div>

    <script src="lib/jquery-2.1.4.js"></script>
    <script src="lib/fastclick.js"></script>
    <script type="text/javascript" src="js/jquery.Spinner.js"></script>
    <script>
      $(function() {
        FastClick.attach(document.body);
      });
    </script>

    <script src="js/jquery-weui.js"></script>
  </body>
</html>

accounts/templates/register.html
{%  extends 'base.html' %}
{% block title %}
<title>手机注册</title>
{% endblock %}
{% block container %}
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">手机注册</div>
    </header>
    <form class="weui-content" method="post" action=".">
       <!--g1GnncJikYPgHlpN1AvUm6NVjnwvdnQ3arJVf1DWyEnDFawHAI59pcc4HQAonyvh-->
      {% csrf_token %}
      <div class="weui-cells weui-cells_form wy-address-edit">
        <div class="weui-cell weui-cell_vcode">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">手机号</label>
          </div>
          <div class="weui-cell__bd">
            <input class="weui-input" type="tel" name="username"
                   placeholder="请输入手机号"
                    value="{{ form.username.value|default_if_none:''}}"/>
          </div>
          <div class="weui-cell__ft">
            <button class="weui-vcode-btn">获取验证码</button>
          </div>
        </div>
          {{ form.username.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">昵称</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="text"
              name="nickname"
              value="{{ form.nickname.value|default_if_none:'' }}"
              placeholder="请输入昵称"
            />
          </div>
        </div>
          {{ form.nickname.errors }}
        <div class="weui-cell weui-cell_vcode">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">验证码</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              name="verify_code"
              type="text"
              placeholder="请输入验证码"
            />
          </div>
          <div class="weui-cell__ft">
            <img class="weui-vcode-img" src="{% url 'system:verify_code' %}" />
          </div>
        </div>
          {{ form.verify_code.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">设置密码</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="password"
              name="password"
              placeholder="请输入新密码"
            />
          </div>
        </div>
          {{ form.password.errors }}
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">确认密码</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="password"
              name="password_repeat"
              placeholder="请再次输入新密码"
            />
          </div>
        </div>
          {{ form.password_repeat.errors }}
          {{ form.non_field_errors }}
      </div>
      <label for="weuiAgree" class="weui-agree">
        <input
          id="weuiAgree"
          type="checkbox"
          class="weui-agree__checkbox"
          checked="checked"
        />
        <span class="weui-agree__text"
          >阅读并同意<a href="javascript:void(0);">《注册协议》</a></span
        >
      </label>
      <div class="weui-btn-area">
          <input class="weui-btn weui-btn_warn" type="submit" value="注册并登陆">
      </div>
      <div class="weui-cells__tips t-c font-12">登陆账号为您输入的手机号码</div>
    </form>
{% endblock %}