accounts/urls.py
from django.conf.urls import url

from accounts import views

urlpatterns = [
    # 用户登录
    url(r'^user/login/$', views.user_login, name='user_login'),
    # 用户退出
    url(r'^user/logout/$', views.user_logout, name='user_logout'),
    # 用户注册
    url(r'^user/register/$', views.user_register, name='user_register'),

    # 地址列表
    url(r'^user/address/list/$', views.address_list, name='address_list'),
    # 地址的修改和编辑
    # user/address/edit/add/   user/address/edit/12/
    url(r'^user/address/edit/(?P<pk>\S+)/$', views.address_edit, name='address_edit'),
    url(r'^user/address/delete/(?P<pk>\d+)/$', views.address_delete, name='address_delete'),

]

django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # django自带的后台管理
    url(r'^admin/', admin.site.urls),
    # xadmin的配置
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # 商品部分
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # 用户账户模块
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # 系统模块
    url(r'^sys/', include('system.urls', namespace='system')),
    # 个人中心
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

mine/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from mine import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # 订单详情
    url(r'^order/detail/(?P<sn>\S+)/$', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    # 添加到购物车
    url(r'^cart/add/(?P<prod_uid>\S+)/$', views.cart_add, name='cart_add'),
    # 我的购物车
    url(r'^cart/$', views.cart, name='cart'),
    # 提交订单
    url(r'^order/pay/$', views.order_pay, name='order_pay'),
    # 我的订单列表
    url(r'^order/list/$', login_required(views.OrderListView.as_view()), name='order_list'),
    # 我的收藏
    url(r'^prod/collect/$', views.prod_collect, name='prod_collect'),
]

system/urls.py
from django.conf.urls import url

from system import views

urlpatterns = [
    # 新闻列表
    url(r'^news/$', views.news_list, name='news_list'),
    # 新闻详情
    url(r'^new/(?P<pk>\d+)/$', views.news_detail, name='news_detail'),

    # 验证码
    url(r'^verify/code/$', views.verify_code, name='verify_code'),
]

system/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models

from utils import constants


class Slider(models.Model):
    """ 系统轮播图 """
    name = models.CharField('名称', max_length=32)
    desc = models.CharField('描述', max_length=100, null=True, blank=True)
    types = models.SmallIntegerField('展现位置',
                                     choices=constants.SLIDER_TYPES_CHOICES,
                                     default=constants.SLIDER_TYPE_INDEX)
    img = models.ImageField('图片', upload_to='slider')
    reorder = models.SmallIntegerField('排序', default=0, help_text='数字越大，越靠前')
    start_time = models.DateTimeField('生效开始时间', null=True, blank=True)
    end_time = models.DateTimeField('生效结束时间', null=True, blank=True)

    target_url = models.CharField('跳转地址', max_length=255, null=True, blank=True)
    is_valid = models.BooleanField('是否删除', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('最后修改时间', auto_now=True)

    class Meta:
        db_table = 'system_slider'
        verbose_name = '轮播图'
        verbose_name_plural = '轮播图'
        ordering = ['-reorder']


class News(models.Model):
    """ 新闻及通知 """
    types = models.SmallIntegerField('类型', choices=constants.NEWS_TYPES_CHOICES,
                                     default=constants.NEWS_TYPE_NEW)
    title = models.CharField('标题', max_length=255)
    content = models.TextField('内容')
    reorder = models.SmallIntegerField('排序', default=0, help_text='数字越大，越靠前')
    start_time = models.DateTimeField('生效开始时间', null=True, blank=True)
    end_time = models.DateTimeField('生效结束时间', null=True, blank=True)
    view_count = models.IntegerField('浏览次数', default=0)

    is_top = models.BooleanField('是否置顶', default=False)
    is_valid = models.BooleanField('是否删除', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('最后修改时间', auto_now=True)

    class Meta:
        db_table = 'system_news'
        verbose_name = '新闻及通知'
        verbose_name_plural = '新闻及通知'
        ordering = ['-reorder']


class ImageFile(models.Model):
    """ 图片表 """
    # 201902/xxxx
    img = models.ImageField('图片', upload_to='%Y%m/images/')
    summary = models.CharField('图片名称', max_length=200)

    # 复合关联
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    is_valid = models.BooleanField('是否有效', default=True)

    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        db_table = 'system_images'
        verbose_name = '图片表'
        verbose_name_plural = '图片表'

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link rel="stylesheet" href="/static/lib/weui.min.css" />
    <link rel="stylesheet" href="/static/css/jquery-weui.css" />
    <link rel="stylesheet" href="/static/css/style.css" />
    {% block title %}
       <meta name="description" content=""/>
       <title>积分商城首页</title>
       {# 页面的头部信息，可添加头部标签，css,js,<title> #}
    {% endblock %}
  </head>
  <body ontouchstart class="container">
    {% block container %}
     {# 页面的内容区域 #}
    {% endblock %}



    <script src="/static/lib/jquery-2.1.4.js"></script>
    <script src="/static/lib/fastclick.js"></script>
    <script src="/static/js/jquery-weui.js"></script>
    <script>
        // 手机端事件穿透
      $(function() {
        FastClick.attach(document.body);
      });
      // 返回事件
        $(".wy-header-icon-back").click(function () {
            history.go(-1);
        })
      {% if messages %}
          {% for msg in messages %}
            $.toptip('{{ msg }}', '{{ msg.tags }}');
          {% endfor %}
      {% endif %}
    </script>
    {% block footer %}
    {#   页面底部，可以用来放html片段，可以添加新的js     #}
    {% endblock %}
  </body>
</html>

templates/footer.html
<!--底部导航-->
<div class="foot-black"></div>
<div class="weui-tabbar wy-foot-menu">
  <a href="{% url 'index' %}"
     class="weui-tabbar__item
    {% if tab == 'index' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-home"></div>
    <p class="weui-tabbar__label">首页</p>
  </a>
  <a href="{% url 'mall:prod_classify' %}"
     class="weui-tabbar__item
    {% if tab == 'classify' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-list"></div>
    <p class="weui-tabbar__label">分类</p>
  </a>
  <a href="{% url 'mine:cart' %}"
     class="weui-tabbar__item
    {% if tab == 'cart' %}weui-bar__item--on {% endif %}">
     {% if cart_count > 0 %}
      <span
      class="weui-badge"
      style="position: absolute;top: -.4em;right: 1em;"
      >{{ cart_count }}</span>
     {% endif %}
    <div class="weui-tabbar__icon foot-menu-cart"></div>
    <p class="weui-tabbar__label">购物车</p>
  </a>
  <a href="{% url 'mine:index' %}"
     class="weui-tabbar__item
    {% if tab == 'mine' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-member"></div>
    <p class="weui-tabbar__label">我的</p>
  </a>
</div>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    <title>积分商城首页, 欢迎光临</title>
{% endblock %}
{% block container %}
    <header class="wy-header">
      <div class="wy-header-title">积分商城</div>
    </header>
    <!--顶部搜索-->
    <header class="weui-header">
      <div class="weui-search-bar" id="searchBar">
        <form class="weui-search-bar__form">
          <div class="weui-search-bar__box">
            <i class="weui-icon-search"></i>
            <input
              type="search"
              class="weui-search-bar__input"
              id="searchInput"
              placeholder="搜索您想要的商品"
              required
            />
            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
          </div>
          <label
            class="weui-search-bar__label"
            id="searchText"
            style="transform-origin: 0px 0px 0px; opacity: 1; transform: scale(1, 1);"
          >
            <i class="weui-icon-search"></i>
            <span>搜索您想要的商品</span>
          </label>
        </form>
        <a
          href="javascript:"
          class="weui-search-bar__cancel-btn"
          id="searchCancel"
          >取消</a
        >
      </div>
    </header>
    {% if user.is_authenticated %}
    <h3>欢迎您， {{ user.username }}</h3>
    {% else %}
        欢迎您， <a href="{% url 'accounts:user_login' %}">请登录</a>
    {% endif %}
    <!--主体-->
    <div class="weui-content">
      <!--顶部轮播-->
      <div class="swiper-container swiper-banner">
        <div class="swiper-wrapper">
          {% for slider in slider_list %}
          <div class="swiper-slide">
            <a href="{{ slider.target_url }}">
                <img src="{{ slider.img }}"/>
            </a>
          </div>
          {% endfor %}
        </div>
        <div class="swiper-pagination"></div>
      </div>
      <!--图标分类-->
      <div class="weui-flex wy-iconlist-box">
        <div class="weui-flex__item">
          <a href="{% url 'mall:product_list' %}?tag=jxtj" class="wy-links-iconlist"
            ><div class="img"><img src="/static/images/icon-link1.png" /></div>
            <p>精选推荐</p></a
          >
        </div>
        <div class="weui-flex__item">
          <a href="{% url 'mall:product_list' %}?cls=jszc" class="wy-links-iconlist"
            ><div class="img"><img src="/static/images/icon-link2.png" /></div>
            <p>酒水专场</p></a
          >
        </div>
        <div class="weui-flex__item">
          <a href="all_orders.html" class="wy-links-iconlist"
            ><div class="img"><img src="/static/images/icon-link3.png" /></div>
            <p>订单管理</p></a
          >
        </div>
        <div class="weui-flex__item">
          <a href="javascript:alert('暂未开放')" class="wy-links-iconlist"
            ><div class="img"><img src="/static/images/icon-link4.png" /></div>
            <p>商家入驻</p></a
          >
        </div>
      </div>
      <!--新闻切换-->
      <div class="wy-ind-news">
        <i class="news-icon-laba"></i>
        <div class="swiper-container swiper-news">
          <div class="swiper-wrapper">
            {% for item in news_list %}
            <div class="swiper-slide">
              <a href="{% url 'system:news_detail' item.pk %}"
                >{{ item.title }}</a
              >
            </div>
             {% endfor %}
          </div>
          <div class="swiper-pagination"></div>
        </div>
        <a href="{% url 'system:news_list' %}" class="newsmore"
          ><i class="news-icon-more"></i
        ></a>
      </div>
      <!--精选推荐-->
      <div class="wy-Module">
        <div class="wy-Module-tit"><span>精选推荐</span></div>
        <div class="wy-Module-con">
          <div
            class="swiper-container swiper-jingxuan"
            style="padding-top:34px;"
          >
            <div class="swiper-wrapper">
              {% for item in jx_list %}
              <div class="swiper-slide">
                <a href="{% url 'mall:product_detail' item.uid %}">
                    <img src="{{ item.img.url }}"/>
                </a>
              </div>
              {% endfor %}
            </div>
            <div class="swiper-pagination jingxuan-pagination"></div>
          </div>
        </div>
      </div>
      <!--酒水专场-->
      <div class="wy-Module">
        <div class="wy-Module-tit"><span>酒水推荐</span></div>
        <div class="wy-Module-con">
          <div
            class="swiper-container swiper-jiushui"
            style="padding-top:34px;"
          >
            <div class="swiper-wrapper">
              {% for item in js_list %}
              <div class="swiper-slide">
                <a href="{% url 'mall:product_detail' item.uid %}">
                    <img src="{{ item.img.url }}"/>
                </a>
              </div>
              {% endfor %}
            </div>
            <div class="swiper-pagination jingxuan-pagination"></div>
          </div>
        </div>
      </div>
      <!--猜你喜欢-->
      <div class="wy-Module">
        <div class="wy-Module-tit-line"><span>猜你喜欢</span></div>
        <div class="wy-Module-con">
          <ul class="wy-pro-list clear">
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro1.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro2.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro3.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro4.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro5.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
            <li>
              <a href="../mall/templates/pro_info.html">
                <div class="proimg"><img src="/static/upload/pro1.jpg" /></div>
                <div class="protxt">
                  <div class="name">
                    洋河蓝色瓶装经典Q7浓香型白酒500ml52度高端纯粮食白酒2瓶装包邮
                  </div>
                  <div class="wy-pro-pri">¥<span>296.00</span></div>
                </div>
              </a>
            </li>
          </ul>
          <div class="morelinks"><a href="../mall/templates/pro_list.html">查看更多 >></a></div>
        </div>
      </div>
    </div>
    {#  包含底部的html模块 #}
    {% include 'footer.html' with tab='index' %}
{%  endblock %}
{% block footer %}
    <script src="/static/js/swiper.js"></script>
    <script>
      $('.swiper-banner').swiper({
        loop: true,
        autoplay: 3000
      });
      $('.swiper-news').swiper({
        loop: true,
        direction: 'vertical',
        paginationHide: true,
        autoplay: 30000
      });
      $('.swiper-jingxuan').swiper({
        pagination: '.swiper-pagination',
        loop: true,
        paginationType: 'fraction',
        slidesPerView: 3,
        paginationClickable: true,
        spaceBetween: 2
      });
      $('.swiper-jiushui').swiper({
        pagination: '.swiper-pagination',
        paginationType: 'fraction',
        loop: true,
        slidesPerView: 3,
        slidesPerColumn: 2,
        paginationClickable: true,
        spaceBetween: 2
      });
    </script>
{% endblock %}